services:
  maze-growth-simulator-dev:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.maze-growth-simulator-dev.rule=Host(`test.simulador.mazefunnels.io`)
      - traefik.http.routers.maze-growth-simulator-dev.entrypoints=websecure
      - traefik.http.routers.maze-growth-simulator-dev.tls.certresolver=letsencrypt
      - traefik.http.services.maze-growth-simulator-dev.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
